// Generated by CoffeeScript 1.3.3
(function() {

  window.plugins.pagefold = {
    emit: function(div, item) {
      return div.append("<div>\n    <span class=\"page-background\">" + item.text + "</span>\n</div>");
    },
    bind: function(div, item) {
      return div.dblclick(function() {
        return wiki.textEditor(div, item);
      });
    }
  };

}).call(this);
